# Created by Blocks_n_more

bot:
  token: "BOT TOKEN" # Discord bot token
  prefixes: # Bot prefix
    - "-"
  status:
    staus: "online" # online | idle | dnd | invisible
    type: "PLAYING" # PLAYING | WATCHING | LISTENING
    message: "With open source code" # Status message
  embed:
    color: "#00FFFF" # Any HEX color code or RANDOM

server:
  roles:
    mod:
      - "1234567890" # Replace with your mod/admin role ids
    admin:
      - "1234567890" # Replace with your mod/admin role ids